=== provenant-dev/public-schema/tn/tn.schema.json
{
  "$id": "EGEebb1pVRcZ6OXHlYitl5DNh-LDrMWPwRtstiKiDhRy",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Telephone Number Credential",
  "description": "Telephone Number Credential issued to a Brand for A2P 10DLC messaging campaigns",
  "type": "object",
  "credentialType": "TelephoneNumberCredential",
  "version": "1.0.0",
  "required": [
    "v",
    "d",
    "u",
    "i",
    "ri",
    "s",
    "a",
    "e",
    "r"
  ],
  "properties": {
    "v": {
      "description": "Version",
      "type": "string"
    },
    "d": {
      "description": "Credential SAID",
      "type": "string"
    },
    "u": {
      "description": "A salty nonce",
      "type": "string"
    },
    "i": {
      "description": "Issuer AID",
      "type": "string"
    },
    "ri": {
      "description": "Credential status registry",
      "type": "string"
    },
    "s": {
      "description": "Schema SAID",
      "type": "string"
    },
    "a": {
      "oneOf": [
        {
          "description": "Attributes block SAID",
          "type": "string"
        },
        {
          "$id": "EPBlIaGwdiP_PaMZHbIOUPtJ20qX4LaHbIzDZT4KAWtt",
          "description": "Attributes block",
          "type": "object",
          "required": [
            "d",
            "u",
            "i",
            "dt",
            "numbers",
            "channel",
            "doNotOriginate",
            "startDate",
            "endDate"
          ],
          "properties": {
            "d": {
              "description": "Attributes block SAID",
              "type": "string"
            },
            "u": {
              "description": "A salty nonce",
              "type": "string"
            },
            "i": {
              "description": "Recipient Brand AID",
              "type": "string"
            },
            "dt": {
              "description": "Issuance date time",
              "format": "date-time",
              "type": "string"
            },
            "numbers": {
              "description": "Telephone Numbers allocated to brand either as a list of specific numbers or a range of numbers",
              "type": "object",
              "properties": {
                "tn": {
                  "description": "Specific telephone numbers list",
                  "type": "array",
                  "uniqueItems": true,
                  "minItems": 1,
                  "items": {
                    "type": "string",
                    "description": "Telephone number in E164 format",
                    "pattern": "[+][0-9]{7,15}"
                  }
                },
                "rangeStart": {
                  "description": "Range start number in E164 format, inclusive of this number. If provided, rangeEnd must also be provided",
                  "type": "string"
                },
                "rangeEnd": {
                  "description": "Range end number in E164 format, inclusive of this number. If provided, rangeStart must also be provided",
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "channel": {
              "description": "Communication channel for which number will be used (e.g., sms, voice, etc.)",
              "type": "string",
              "pattern": "sms|voice"
            },
            "doNotOriginate": {
              "description": "True or False based on condition if telephone number is a 'do not originate' number (inbound only)",
              "type": "boolean"
            },
            "startDate": {
              "description": "Start date",
              "format": "date-time",
              "type": "string"
            },
            "endDate": {
              "description": "Expiration date",
              "format": "date-time",
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "e": {
      "oneOf": [
        {
          "description": "Edges block SAID",
          "type": "string"
        },
        {
          "$id": "EJrEovSBvm4odgfVI9zldtlju8_lD2m1gDiryDqvB8Lt",
          "description": "Edges block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Edges block SAID",
              "type": "string"
            },
            "le": {
              "description": "Chain to legal entity vLEI credential",
              "type": "object",
              "properties": {
                "n": {
                  "description": "SAID of Legal Entity vLEI Credential issued by a Qualified vLEI issuer to a Legal Entity",
                  "type": "string"
                },
                "s": {
                  "description": "SAID of Legal Entity vLEI Credential schema",
                  "type": "string",
                  "const": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "le"
          ]
        }
      ]
    },
    "r": {
      "oneOf": [
        {
          "description": "Rules section SAID",
          "type": "string"
        },
        {
          "$id": "EHIN5MfIpe7_by-Rl7oVK6dDg1o096wds_gwtcsZInzj",
          "description": "Rules detail",
          "type": "object",
          "required": [
            "d",
            "perBrand"
          ],
          "properties": {
            "d": {
              "description": "Rule section SAID",
              "type": "string"
            },
            "perBrand": {
              "description": "perBrand Disclaimer",
              "oneOf": [
                {
                  "description": "simple compact rule form",
                  "type": "string",
                  "const": "Issuees agree not to share the phone number with other brands which may have a common owner but which will make it difficult to consistently identify the originator of traffic."
                },
                {
                  "description": "Rule detail",
                  "type": "object",
                  "properties": {
                    "l": {
                      "description": "Associated legal language",
                      "type": "string",
                      "const": "Issuees agree not to share the phone number with other brands which may have a common owner but which will make it difficult to consistently identify the originator of traffic."
                    }
                  },
                  "required": [
                    "l"
                  ],
                  "additionalProperties": false
                }
              ]
            }
          },
          "additionalProperties": false
        }
      ]
    }
  },
  "additionalProperties": false
}

=== provenant-dev/public-schema/tn/example-tn.json
{
  "v": "ACDC10JSON00040c_",
  "d": "EHhWLa-wy3agU2XrBQva9Aa_fn1quykH0g8VbEWLg4Oz",
  "u": "0AD5Y0r_UJ3OaDC9ww7UcwMX",
  "i": "EPf-n0htLTtNESESLTt4BuE-jadJtkomCNxlzos9pMOV",
  "ri": "ENcuoFsOMgygryMcsWpMEoAwY9gzJGLmApjC6nVeFE9m",
  "s": "EGEebb1pVRcZ6OXHlYitl5DNh-LDrMWPwRtstiKiDhRy",
  "a": {
    "d": "EPCnmKoZ8Sf_9QykiwXih2qjFveHcrhP0BVKSWd6ajpC",
    "u": "0AB2S1oIA7MZcGgYMPnsQeCy",
    "i": "EMqWlrNiLIyzsCebjb7mrGtn6RHNE359Y4iJSAmVMWdW",
    "dt": "2024-12-17T11:22:07.958000+00:00",
    "numbers": {
      "rangeStart": "+1801361002",
      "rangeEnd": "+1801361009"
    },
    "channel": "voice",
    "doNotOriginate": false,
    "startDate": "2024-12-25T20:20:39+00:00",
    "endDate": "2024-11-29T20:20:39+00:00"
  },
  "e": {
    "d": "ELgUHQasEuGtntBtXLE7zlxFYTR5vRi8M3GMgqHxWVYN",
    "le": {
      "n": "EJDQgxYJJR_4AZwcjrdwQASgVwdYb0VfQskrFkGnVbUw",
      "s": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
    }
  },
  "r": {
    "d": "EJFhpp0uU7D7PKooYM5QIO1hhPKTjHE18sR4Dn0GFscR",
    "perBrand": "Issuees agree not to share the phone number with other brands which may have a common owner but which will make it difficult to consistently identify the originator of traffic."
  }
}
