=== provenant-dev/public-schema/brand-owner/brand-owner.schema.json
{
  "$id": "EBpGNZSWwj-btOJMJSMLCVoXbtKdJTcggO-zMevr4vH_",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Brand Owner Credential",
  "description": "Issued to a legal entity that has the right to use a brand because it is the direct owner or a licensee of that brand.",
  "type": "object",
  "credentialType": "BrandOwnerCredential",
  "version": "1.0.0",
  "properties": {
    "v": {
      "description": "Version",
      "type": "string"
    },
    "d": {
      "description": "Credential SAID",
      "type": "string"
    },
    "u": {
      "description": "One time use nonce",
      "type": "string"
    },
    "i": {
      "description": "Issuer AID",
      "type": "string"
    },
    "ri": {
      "description": "Credential status registry",
      "type": "string"
    },
    "s": {
      "description": "Schema SAID",
      "type": "string"
    },
    "a": {
      "oneOf": [
        {
          "description": "Attributes block SAID",
          "type": "string"
        },
        {
          "$id": "EIDYFHkBOgNVWGFRcN1cEXNvRV47-nrNJGx6mKHBA7ia",
          "description": "Attributes block",
          "type": "object",
          "properties": {
            "d": {
              "description": "Attributes block SAID",
              "type": "string"
            },
            "i": {
              "description": "AID of the legal entity that is the direct owner or a licensee of the brand",
              "type": "string"
            },
            "dt": {
              "description": "Issuance date time",
              "format": "date-time",
              "type": "string"
            },
            "vcard": {
              "description": "An ordered list of unfolded, VCard content lines (properties) per RFC 6350, where property and parameter names are upper case, and parameter names appear in lexicographic order. Values that are telephone numbers MUST be in strict E164 format with a leading + but no other spaces or punctuation. The CHATBOT property is standard and is of type URI. If the type of a particular value is URI and refers to static media files (as, for example, with LOGO), the HASH parameter SHOULD be included and MUST be the CESR-encoded value of the content at the URI. Alternatively, data URIs MAY be used. A URI that refers to mutable content SHOULD NOT be used, as it is insecure; if present, the credential is asserting only the location, not the content of the logo.",
              "type": "array",
              "uniqueItems": true,
              "minItems": 1,
              "items": {
                "format": "cesr",
                "type": "string"
              },
              "examples": [
                "ORG:Example Company UK, Ltd",
                "NICKNAME:Examples-R-Us",
                "CHATBOT:https://example.com/chatwithus",
                "LOGO;HASH=EK2r6EnDXre2pecTBO8s99j4OtNaaDIhVyr7uGugDhmp;VALUE=URI:https://example.com/logo64x48.png",
                "TEL;TYPE=support:+445555555555",
                "EMAIL:support@example.com",
                "URL:https://www.example.com",
                "ADR;TYPE=work:;;123 Example Street;London;;SW1A 1AA;United Kingdom",
                "GEO:51.5074;-0.1278",
                "TZ:Europe/London",
                "LANG:en-GB"
              ]
            },
            "goals": {
              "description": "Goal codes (see https://bit.ly/49V8YqV) that enumerate formally-defined activities in which the brand's owner might engage using the asserted brand attributes. If specified, activities not covered by these goal codes are considered contexts in which the legitimate use of the brand is not asserted by this credential.",
              "type": "array",
              "uniqueItems": true,
              "minItems": 1,
              "items": {
                "format": "cesr",
                "type": "string"
              }
            }
          },
          "additionalProperties": true,
          "required": [
            "i",
            "dt"
          ]
        }
      ]
    },
    "e": {
      "oneOf": [
        {
          "description": "Edges block SAID",
          "type": "string"
        },
        {
          "$id": "EGt3Q1rQJweeryWfJGBYlKCFsYbNrYGYc6AaTRBzwzHG",
          "description": "Edges detail",
          "type": "object",
          "required": [
            "d",
            "issuer"
          ],
          "properties": {
            "d": {
              "description": "Edges block SAID",
              "type": "string"
            },
            "issuer": {
              "description": "Edge credential that proves the identity of the issuer.",
              "type": "object",
              "properties": {
                "n": {
                  "description": "SAID of a credential that proves the identity of the issuer",
                  "type": "string"
                },
                "s": {
                  "description": "SAID of credential schema that proves the identity of the issuer",
                  "type": "string"
                },
                "o": {
                  "description": "Operator indicating issuer AID of this ACDC MUST be the Issuee AID of the node this Edge points to.",
                  "type": "string",
                  "const": "I2I"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s",
                "o"
              ]
            },
            "brandauth": {
              "description": "Edge credential that proves the brand authority.",
              "type": "object",
              "properties": {
                "n": {
                  "description": "SAID of a credential that proves the brand authority",
                  "type": "string"
                },
                "s": {
                  "description": "SAID of credential schema that proves the brand authority",
                  "type": "string"
                },
                "o": {
                  "description": "Operator indicating issuer AID of this ACDC MUST be the Issuee AID of the node this Edge points to.",
                  "type": "string",
                  "const": "I2I"
                }
              },
              "additionalProperties": false,
              "required": [
                "n",
                "s",
                "o"
              ]
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "r": {
      "oneOf": [
        {
          "description": "Rules section SAID",
          "type": "string"
        },
        {
          "$id": "EGFgHT7Xrzy9YLdQNXnNTYVBu9_Q0O7K5A2VCWjg93t3",
          "description": "Rules detail",
          "type": "object",
          "properties": {
            "d": {
              "description": "Rule section SAID",
              "type": "string"
            }
          },
          "additionalProperties": true,
          "required": [
            "d"
          ]
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "ri",
    "s",
    "d",
    "r"
  ]
}

=== provenant-dev/public-schema/gcd/example.json
{
    "v": "ACDC10JSON00096c_",
    "d": "EDQpU3nrKyJBgUJGw5461CbWcug9BZj7WXUkKbNOlnFR",
    "u": "0ADE6oAxBl4E7uKeGUb7BEYi",
    "i": "EC4SuEyzrRwu3FWFrK0Ubd9xejlo5bUwAtGcbBGUk2nL",
    "ri": "EM2YZ78SKE8eO4W1lQOJeer5xKZqLmJV7SPr3Ji5DMBZ",
    "s": "EL7irIKYJL9Io0hhKSGWI4OznhwC7qgJG5Qf4aEs6j0o",
    "a": {
        "d": "EPQhEk5tfXvxyKe5Hk4DG63dSgoP-F2VZrxuIeIKrT9B",
        "u": "0AC9kH8q99PTCQNteGyI-F4g",
        "i": "EIkxoE8eYnPLCydPcyc_lhQgwOdBHwzkSe36e2gqEH-5",
        "dt": "2024-12-27T13:11:29.062000+00:00",
        "role": "Example role description",
        "c_goal": [
            "meetupcorp.personal.date"
        ],
        "c_pgeo": [
            "US"
        ],
        "c_rgeo": [
            "US"
        ],
        "c_proto": [
            "proto:exp"
        ],
        "c_human": "",
        "c_after": "2024-12-17T10:39:29.769000+00:00",
        "c_before": "2025-12-17T10:39:29.769000+00:00"
    },
    "e": {
        "d": "EGbMyeCJ9ERVz7GfaS7V-nNvqeSYmg3q6rW7czGyad6m",
        "issuer": {
            "n": "EIpaOx1NJc0N_Oj5xzWhFQp6EpB847yTex62xQ7uuSQL",
            "s": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY",
            "o": "I2I"
        }
    },
    "r": {
        "d": "EFthNcTE20MLMaCOoXlSmNtdooGEbZF8uGmO5G85eMSF",
        "noRoleSemanticsWithoutGfw": "All parties agree that the role field has no enforceable semantics unless the gfw field is also defined, and its rules formally describe what the role means.",
        "issuerNotResponsibleOutsideConstraints": "Although verifiers set their own standards for verification, verifiers and issuees/delegates agree that they cannot not use this credential as proof that delegator has the right to exercise delegated authority under conditions when the constraints say otherwise.",
        "noConstraintSansPrefix": "Issuers agree that constraints exist only in fields with the c_ prefix, or in the role field with gfw defined. This allows verifiers to know with confidence whether all constraints have been satisfied, even if they do not understand some custom fields that lack the prefix.",
        "useStdIfPossible": "Issuers agree that if it is reasonable to express a constraint in one of the pre-defined ways, they will do so, rather than expressing the constraint in a note or in a custom field. This allows verifiers to be confident that when one of the pre-defined constraints is absent, delegated authority is unconstrained in its corresponding dimension.",
        "onlyDelegateHeldAuthority": "Issuers agree to only delegate authority that they reasonably believe they hold. Whether they do in fact hold that authority is still a matter for verifiers to evaluate (e.g., via edges or separate proving interactions), but this rule creates a modest accountability for data quality."
    }
}
